### ISSUE TITLE
New-ADUser : Une valeur de l’attribut n’était pas dans la plage de valeurs acceptables

### ISSUE THREAD

**Issue by DCx14** [qschweitzer/Generate-ADUsersRandomly#1]
Lignes 226:

"New-ADUser -Path $OU -DisplayName $DisplayName -AccountPassword $Password -SamAccountName $SamAccountName -UserPrincipalName $UserPrincipalName -GivenName $GivenName -Surname $SurName -Name $DisplayName -Enabled $true -City $City -State $State  -StreetAddress $Address -EmailAddress $Email -OfficePhone $OfficePhone -Office $Office -PostalCode $PostalCode -MobilePhone $MobilePhone -ErrorAction SilentlyContinue -ErrorVariable erroruser"

Please delete "-Country $Country"

Try again

**Comment by qschweitzer** [comment]
Hey,
Sorry for the long time without comment.
Yep, you're right, that's not needed.
I already have deleted it at that time.
